/**
 * Builds the default e-mails: `maizzle build` in `mail/`, which writes the
 * HTML and text of each e-mail per locale, and the manifest, to `mails/` —
 * and `src/generated/mail.ts`, the e-mails' variables as a type.
 *
 * Then, from the manifest:
 *
 * - it **fails unless the manifest's format is the one `@nxgt/mail-i18n`
 *   writes, and one `@nxgt/mail` 0.1.0 reads** — the peer is `>=0.1.0 <2`, and
 *   a renderer reads every format up to its own, so a newer format would
 *   break an application on the floor;
 * - it **fails unless exactly the twelve e-mails** of Janus's flows were built,
 *   so a preset added or dropped by a new `@nxgt/mail-presets` is a failed
 *   build here, not a surprise in a consumer's outbox;
 * - it writes `src/generated/locales.ts` — the locales built, as a type —
 *   and `src/generated/codes-left.ts` — the plural of the recovery codes
 *   left, in each of them (`./codes-left`) — **only when its content
 *   changed**, so a build that changes nothing leaves the tree clean and
 *   CI's `git diff --exit-code` on `src/generated` holds.
 *
 * Run by the package's `build`, before `../../build.ts`: the TypeScript build
 * reads what this one generated. No consumer ever runs it — the package ships
 * `mails/`, and needs no Maizzle at run time.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { MANIFEST_FORMAT } from '@nxgt/mail-i18n';
import { $ } from 'bun';
import { branchesOf, codesLeftMessage, codesLeftModule } from './codes-left';

/** The e-mails the package promises, sorted as the manifest sorts them. */
export const EXPECTED_EMAILS = [
	'confirm-action',
	'email-changed',
	'magic-link',
	'new-sign-in',
	'password-changed',
	'recovery-code-used',
	'reset-password',
	'sign-in-code',
	'two-factor-disabled',
	'two-factor-enabled',
	'verify-email',
	'welcome',
] as const;

const MAIL_DIR = fileURLToPath(new URL('../mail/', import.meta.url));
const MANIFEST = fileURLToPath(
	new URL('../mails/mail-manifest.json', import.meta.url),
);
const LOCALES_MODULE = fileURLToPath(
	new URL('../src/generated/locales.ts', import.meta.url),
);
const CODES_LEFT_MODULE = fileURLToPath(
	new URL('../src/generated/codes-left.ts', import.meta.url),
);

/**
 * The newest manifest format the oldest `@nxgt/mail` the peer admits reads:
 * `>=0.1.0 <2`, and 0.1.0 through 0.5.0 read format 1 only. They export no
 * `MANIFEST_FORMAT`, so the number is written here, and raising it means
 * raising the peer's floor to the first `@nxgt/mail` that reads the new format.
 */
export const PEER_FLOOR_READS = 1;

/** The part of the manifest this script reads. */
interface BuiltManifest {
	readonly formatVersion?: unknown;
	readonly locales: readonly string[];
	readonly emails: Readonly<Record<string, unknown>>;
}

/**
 * Why the manifest's format is not one the package can ship, or `null` when
 * it is: it must be the format this `@nxgt/mail-i18n` writes (`written`) —
 * anything else is a `mails/` left by another build — and no newer than what
 * the peer's floor reads (`readable`), or an application on that
 * `@nxgt/mail` fails at start-up.
 */
export function formatProblem(
	manifest: BuiltManifest,
	written: number,
	readable: number = PEER_FLOOR_READS,
): string | null {
	const format = manifest.formatVersion;
	if (format !== written) {
		return (
			`build-mail: mails/mail-manifest.json is manifest format ${String(format)}, ` +
			`where @nxgt/mail-i18n writes ${written} — a mails/ left by another build; run the build again`
		);
	}
	if (format > readable) {
		return (
			`build-mail: mails/mail-manifest.json is manifest format ${format}, and @nxgt/mail 0.1.0, ` +
			`the peer's floor, reads up to ${readable} — raise the @nxgt/mail peer's floor to the first version that reads it`
		);
	}
	return null;
}

/** Why a manifest is not the build the package promises, or `null` when it is. */
export function emailsProblem(manifest: BuiltManifest): string | null {
	const built = Object.keys(manifest.emails).sort();
	const same =
		built.length === EXPECTED_EMAILS.length &&
		built.every((email, i) => email === EXPECTED_EMAILS[i]);
	if (same) return null;
	return (
		`build-mail: the build holds ${built.join(', ') || 'no e-mail'}, ` +
		`where the package promises exactly ${EXPECTED_EMAILS.join(', ')}`
	);
}

/** The source of `src/generated/locales.ts` for the locales built, in the manifest's order. */
export function localesModule(locales: readonly string[]): string {
	const list = locales.map((locale) => `'${locale}'`).join(', ');
	return [
		'// Generated by scripts/build-mail.ts from mails/mail-manifest.json, after',
		'// each build of the default e-mails. Never edited; committed.',
		'',
		'/** The locales the default e-mails are built in, the fallback locale first. */',
		`export const LOCALES = [${list}] as const;`,
		'',
		'/** A locale the default e-mails are built in. */',
		'export type JanusMailLocale = (typeof LOCALES)[number];',
		'',
	].join('\n');
}

/** Writes `source` to `path` unless it already holds it: an unchanged build leaves the tree clean. */
async function writeIfChanged(path: string, source: string): Promise<void> {
	const current = await Bun.file(path)
		.text()
		.catch(() => null);
	if (current !== source) writeFileSync(path, source);
}

async function main(): Promise<void> {
	const build = await $`maizzle build`.cwd(MAIL_DIR).nothrow();
	if (build.exitCode !== 0) {
		console.error('build-mail: maizzle build failed — see its output above');
		process.exit(1);
	}

	const manifest: BuiltManifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
	for (const problem of [
		formatProblem(manifest, MANIFEST_FORMAT),
		emailsProblem(manifest),
	]) {
		if (problem !== null) {
			console.error(problem);
			process.exit(1);
		}
	}

	await writeIfChanged(LOCALES_MODULE, localesModule(manifest.locales));
	await writeIfChanged(
		CODES_LEFT_MODULE,
		codesLeftModule(
			Object.fromEntries(
				manifest.locales.map((locale) => [
					locale,
					branchesOf(locale, codesLeftMessage(locale)),
				]),
			),
		),
	);

	console.log(
		`@nxgt/janus-mail: ${EXPECTED_EMAILS.length} e-mails built in ${manifest.locales.join(', ')}`,
	);
}

if (import.meta.main) await main();
