/**
 * Builds the default e-mails: `maizzle build` in `mail/`, which writes the
 * HTML and text of each e-mail per locale, and the manifest, to `mails/` —
 * and `src/generated/mail.ts`, the e-mails' variables as a type.
 *
 * Then, from the manifest:
 *
 * - it **fails unless exactly the five e-mails** of Janus's flows were built,
 *   so a preset added or dropped by a new `@nxgt/mail-presets` is a failed
 *   build here, not a surprise in a consumer's outbox;
 * - it writes `src/generated/locales.ts` — the locales built, as a type —
 *   **only when its content changed**, so a build that changes nothing leaves
 *   the tree clean and CI's `git diff --exit-code` on `src/generated` holds.
 *
 * Run by the package's `build`, before `../../build.ts`: the TypeScript build
 * reads what this one generated. No consumer ever runs it — the package ships
 * `mails/`, and needs no Maizzle at run time.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { $ } from 'bun';

/** The e-mails the package promises, sorted as the manifest sorts them. */
export const EXPECTED_EMAILS = [
	'email-changed',
	'password-changed',
	'reset-password',
	'sign-in-code',
	'verify-email',
] as const;

const MAIL_DIR = fileURLToPath(new URL('../mail/', import.meta.url));
const MANIFEST = fileURLToPath(
	new URL('../mails/mail-manifest.json', import.meta.url),
);
const LOCALES_MODULE = fileURLToPath(
	new URL('../src/generated/locales.ts', import.meta.url),
);

/** The part of the manifest this script reads. */
interface BuiltManifest {
	readonly locales: readonly string[];
	readonly emails: Readonly<Record<string, unknown>>;
}

/** Why a manifest is not the build the package promises, or `null` when it is. */
export function emailsProblem(manifest: BuiltManifest): string | null {
	const built = Object.keys(manifest.emails).sort();
	const same =
		built.length === EXPECTED_EMAILS.length &&
		built.every((email, i) => email === EXPECTED_EMAILS[i]);
	if (same) return null;
	return (
		`build-mail: the build holds ${built.join(', ') || 'no e-mail'}, ` +
		`where the package promises exactly ${EXPECTED_EMAILS.join(', ')}`
	);
}

/** The source of `src/generated/locales.ts` for the locales built, in the manifest's order. */
export function localesModule(locales: readonly string[]): string {
	const list = locales.map((locale) => `'${locale}'`).join(', ');
	return [
		'// Generated by scripts/build-mail.ts from mails/mail-manifest.json, after',
		'// each build of the default e-mails. Never edited; committed.',
		'',
		'/** The locales the default e-mails are built in, the fallback locale first. */',
		`export const LOCALES = [${list}] as const;`,
		'',
		'/** A locale the default e-mails are built in. */',
		'export type JanusMailLocale = (typeof LOCALES)[number];',
		'',
	].join('\n');
}

async function main(): Promise<void> {
	const build = await $`maizzle build`.cwd(MAIL_DIR).nothrow();
	if (build.exitCode !== 0) {
		console.error('build-mail: maizzle build failed — see its output above');
		process.exit(1);
	}

	const manifest: BuiltManifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
	const problem = emailsProblem(manifest);
	if (problem !== null) {
		console.error(problem);
		process.exit(1);
	}

	const source = localesModule(manifest.locales);
	const current = await Bun.file(LOCALES_MODULE)
		.text()
		.catch(() => null);
	if (current !== source) writeFileSync(LOCALES_MODULE, source);

	console.log(
		`@nxgt/janus-mail: ${EXPECTED_EMAILS.length} e-mails built in ${manifest.locales.join(', ')}`,
	);
}

if (import.meta.main) await main();
