/**
 * `src/generated/codes-left.ts`: the sentence the `recovery-code-used` e-mail
 * shows for the codes left, in each locale built.
 *
 * The build cannot write it into the e-mail: the count is only known at send
 * time, and a plural picks its branch from it. So `@nxgt/mail-presets` ships
 * the sentence as a message the template does not read,
 * `recovery-code-used.codes-left` — an ICU plural on `recoveryCodesLeft` —
 * and the sender formats it. `@nxgt/mail-i18n`'s `createTranslator` does,
 * but it is build-only here, as the presets are: nothing Maizzle reaches a
 * consumer's install. This script parses the message at our build instead,
 * and writes its branches as data; `src/codes-left.ts` picks one with
 * `Intl.PluralRules` at send time, and `src/codes-left.spec.ts` holds the
 * result equal to `createTranslator`'s.
 *
 * The message is the one the build reads: `mail/locales/<locale>.json`'s
 * `recovery-code-used.codes-left` when it overrides it, else the preset's.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
	type MessageFormatElement,
	parse,
	TYPE,
} from '@formatjs/icu-messageformat-parser';
import { presetCatalogues } from '@nxgt/mail-presets';

/** One branch of the plural: its text, with `null` where the count goes. */
export type Branch = readonly (string | null)[];

/** The branches of one locale's plural, by selector: `=0`, `one`, `other`… */
export type Branches = Readonly<Record<string, Branch>>;

const LOCALES_DIR = fileURLToPath(new URL('../mail/locales/', import.meta.url));

/** A catalogue's `recovery-code-used.codes-left`, or `undefined`. */
export function lookup(catalogue: unknown): string | undefined {
	const group =
		typeof catalogue === 'object' && catalogue !== null
			? (catalogue as Record<string, unknown>)['recovery-code-used']
			: undefined;
	const message =
		typeof group === 'object' && group !== null
			? (group as Record<string, unknown>)['codes-left']
			: undefined;
	return typeof message === 'string' ? message : undefined;
}

/** The message the build reads for `locale`: its override, else the preset's. */
export function codesLeftMessage(locale: string): string {
	return messageOf(
		locale,
		JSON.parse(readFileSync(`${LOCALES_DIR}${locale}.json`, 'utf8')),
		(presetCatalogues as Readonly<Record<string, unknown>>)[locale],
	);
}

/** `override`'s message, else `preset`'s, else an error naming `locale`. */
export function messageOf(
	locale: string,
	override: unknown,
	preset: unknown,
): string {
	const message = lookup(override) ?? lookup(preset);
	if (message === undefined) {
		throw new Error(
			`build-mail: ${locale} has no recovery-code-used.codes-left — add it to mail/locales/${locale}.json`,
		);
	}
	return message;
}

/** A branch's parts, or an error naming what the sentence may not hold. */
function branchOf(locale: string, elements: MessageFormatElement[]): Branch {
	return elements.map((element) => {
		if (element.type === TYPE.literal) return element.value;
		if (element.type === TYPE.pound) return null;
		throw new Error(
			`build-mail: ${locale}'s recovery-code-used.codes-left holds something other than text and # in a branch`,
		);
	});
}

/**
 * The branches of `message`, which must be one cardinal plural on
 * `recoveryCodesLeft`, with no offset, holding only text and `#`: the
 * preset's shape. Anything else fails the build, since the send could not
 * format it.
 */
export function branchesOf(locale: string, message: string): Branches {
	const [plural, ...rest] = parse(message);
	if (
		plural === undefined ||
		rest.length > 0 ||
		plural.type !== TYPE.plural ||
		plural.value !== 'recoveryCodesLeft' ||
		plural.pluralType !== 'cardinal' ||
		plural.offset !== 0 ||
		plural.options['other'] === undefined
	) {
		throw new Error(
			`build-mail: ${locale}'s recovery-code-used.codes-left must be one plural on recoveryCodesLeft, with an other branch and no offset`,
		);
	}
	return Object.fromEntries(
		Object.entries(plural.options).map(([selector, option]) => [
			selector,
			branchOf(locale, option.value),
		]),
	);
}

/** The source of `src/generated/codes-left.ts` for the locales built. */
export function codesLeftModule(
	branches: Readonly<Record<string, Branches>>,
): string {
	return [
		'// Generated by scripts/build-mail.ts from recovery-code-used.codes-left, after',
		'// each build of the default e-mails. Never edited; committed.',
		'',
		"/** Each locale's plural for the recovery codes left: branches by selector, `null` where the count goes. */",
		`export const CODES_LEFT: Readonly<Record<string, Readonly<Record<string, readonly (string | null)[]>>>> = ${JSON.stringify(branches, null, '\t')};`,
		'',
	].join('\n');
}
